import { ReactNode } from "react";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { AUTH_KEY } from "@/constants/auth.constant";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Sign Up | Rafl",
  description: "Generated by Rafl",
};

export default async function SignUpLayout({
  children,
}: {
  children: ReactNode;
}) {
  await getToken();

  return <>{children}</>;
}

async function getToken() {
  const nextCookies = await cookies(); // Get cookies object
  const cookie = nextCookies.get(AUTH_KEY); // Find cookie
  if (cookie?.value) {
    redirect("/accounts");
  }
}
